import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'

import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from './routes/root/components'
import { Navbar, Footer } from '@/components/Shared'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider >
      <html lang="en">
        <body className={`${geistSans.className} ${geistMono.variable} antialiased min-h-screen`}>
          <SidebarProvider>
            <AppSidebar />
            <div className='w-full bg-stone-100 flex flex-col min-h-screen'>
              <Navbar />
              <main className="flex-1">{children}</main>
              <Toaster />
            </div>

          </SidebarProvider>
         
        </body>
      </html>
    </ClerkProvider>
  )
}
